name: Tag on Push to Main

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      
      - name: install dependencies
        run: npm ci

      - name: lint
        run: npm run type-check && npm run lint

  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # NOTE @v2 uses the token as an auth http header. Set it to
          # a Personal Access Token instead of secrets.GITHUB_TOKEN
          # so that tag pushes trigger repo push events.
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag "build-$(git log -1 --format=%cd --date=format:%Y%m%d%H%M%S)-${GITHUB_SHA::8}"
          git push origin "build-${GITHUB_SHA::8}"
