name: Build and Release Electron App (Cross Platform)

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Electron app
        run: yarn dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ matrix.os }}
          path: dist/*
  
      - name: Get screenshot URL
        id: get-url
        run: |
          # Use GitHub API to get the asset's URL
          URL=$(curl -sH "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref }} \
              | jq '.assets[] | select(.name == "screenshot.png") | .browser_download_url')
          echo "::set-output name=screenshot_url::$URL"

      - name: Release with screenshot in body
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app-windows-latest.zip
            app-ubuntu-latest.zip
            screenshot.png
          tag_name: ${{ github.ref }}
          body: |
            Release for ${{ github.ref }}
          draft: false
          prerelease: false
